### PR TITLE
add gitignore; update dockerfile

### PR DESCRIPTION
**Pull request by gabicavalcante**

### CODE REVIEW

**Review by D3f0 — APPROVED** [review]
I haven't been using this image since last year. This PR looks good, I'm curious on the 17.10 to 17.04 change, but I suppose this may be rooted on some specific dependency on the numerous packages CORE uses.

**Comment by D3f0** [comment]
No objections on merging once the WIP is gone from the title. I suppose students may find valuable to have an updated image.

**Comment by gabicavalcante** [comment]
Hi! I'm using this image to my class of network and security in Brazil, to learn about iptable (in my computer I can't install the CORE), but I had some issues because the dependency. I'm trying to fix it, when I finish I'll remove the WIP :)

**Comment by gabicavalcante** [comment]
@D3f0 PR done

**Comment by D3f0** [comment]
@gabicavalcante thank you for the contribution :)

**Pull request merged**
